<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-23 08:47
=======
# Generated by Django 5.2.8 on 2025-11-23 07:30
>>>>>>> 13a6abb53917f18b0dca32157c6d561ed938d84b

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.TextField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
