<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-23 08:47
=======
# Generated by Django 5.2.8 on 2025-11-23 07:30
>>>>>>> 13a6abb53917f18b0dca32157c6d561ed938d84b

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('type', models.CharField(choices=[('double_room', 'Double'), ('single_room', 'Single')], max_length=20)),
<<<<<<< HEAD
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_maintenance', 'Under Maintenance')], max_length=50)),
=======
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_maintenance', 'Under Maintenance')])),
>>>>>>> 13a6abb53917f18b0dca32157c6d561ed938d84b
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='room_images/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
