# Generated by Django 5.2.8 on 2025-11-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField()),
                ('staying_people', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Customer.customer')),
                ('room_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='Room.room')),
            ],
        ),
    ]
